# Generated by Django 2.2.5 on 2020-10-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='用户组名')),
            ],
            options={
                'verbose_name': '用户组表',
                'db_table': 'tb_groups',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('gender', models.BooleanField(default=False, verbose_name='性别')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Group', verbose_name='用户组')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'tb_users',
            },
        ),
    ]
